[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=allure-results --log-cli-level=INFO --log-file=logs/pytest.log --log-file-level=INFO
markers =
    slow: медленные тесты
    smoke: дымовые тесты
    regression: регрессионные тесты