name: QA Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies for QA
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone and setup the website
      run: |
        cd ..
        git clone https://github.com/ShurikPozd/pivnica_portal.git
        cd pivnica_portal
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py runserver 8000 &
        sleep 5  # Ждём, пока сервер запустится

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run tests
      run: |
        cd ../qa_pivnica
        pytest -v --alluredir=allure-results

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results